services:
  db:
    container_name: mongodb-container
    image: mongo:8.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
